language: go
# see https://docs.travis-ci.com/user/reference/overview/#Virtualization-environments
# for the detail
sudo: requried
dist: bionic

env:
  global:
    - GO111MODULE=on

script:
  - sudo go test -v ./api
