nodes:
  - name: R1
    image: akiranet24/frr:1.0
    interfaces:
        - inf: net0
          type: direct
          ipv6: 2000::1/64
          peernode: R2
          peerinf: net0
        - inf: net1
          type: direct
          ipv6: 2001::1/64
          peernode: R3
          peerinf: net0
    sysctls:
        - sysctl: net.ipv4.ip_forward=1
        - sysctl: net.ipv4.conf.all.rp_filter=0
        - sysctl: net.ipv4.conf.lo.rp_filter=0
        - sysctl: net.ipv6.conf.all.disable_ipv6=0
        - sysctl: net.ipv6.conf.all.forwarding=1
        - sysctl: net.ipv6.conf.all.seg6_enabled=1
        - sysctl: net.ipv6.conf.default.seg6_enabled=1
  - name: R2
    image: akiranet24/frr:1.0
    interfaces:
        - inf: net0
          type: direct
          ipv6: 2000::2/64
          peernode: R1
          peerinf: net0
        - inf: net1
          type: direct
          ipv6: 2001::10/64
          peernode: R4
          peerinf: net0
    sysctls:
        - sysctl: net.ipv4.ip_forward=1
        - sysctl: net.ipv4.conf.all.rp_filter=0
        - sysctl: net.ipv4.conf.lo.rp_filter=0
        - sysctl: net.ipv6.conf.all.disable_ipv6=0
        - sysctl: net.ipv6.conf.all.forwarding=1
        - sysctl: net.ipv6.conf.all.forwarding=1
        - sysctl: net.ipv6.conf.all.seg6_enabled=1
        - sysctl: net.ipv6.conf.default.seg6_enabled=1
  - name: R3
    image: akiranet24/frr:1.0
    interfaces:
        - inf: net0
          type: direct
          ipv6: 2001::2/64
          peernode: R1
          peerinf: net1
        - inf: net1
          type: direct
          ipv4: 10.10.1.1/24
          peernode: S11
          peerinf: net0
        - inf: net1
          type: direct
          ipv4: 10.20.1.1/24
          peernode: S21
          peerinf: net0
    sysctls:
        - sysctl: net.ipv4.ip_forward=1
        - sysctl: net.ipv4.conf.all.rp_filter=0
        - sysctl: net.ipv4.conf.lo.rp_filter=0
        - sysctl: net.ipv6.conf.all.disable_ipv6=0
        - sysctl: net.ipv6.conf.all.forwarding=1
        - sysctl: net.ipv6.conf.all.forwarding=1
        - sysctl: net.ipv6.conf.all.seg6_enabled=1
        - sysctl: net.ipv6.conf.default.seg6_enabled=1
  - name: R4
    image: akiranet24/frr:1.0
    interfaces:
        - inf: net0
          type: direct
          ipv6: 2001::20/64
          peernode: R2
          peerinf: net1
        - inf: net1
          type: direct
          ipv4: 10.10.2.1/24
          peernode: S12
          peerinf: net0
        - inf: net2
          type: direct
          ipv4: 10.20.2.1/24
          peernode: S22
          peerinf: net0
    sysctls:
        - sysctl: net.ipv4.ip_forward=1
        - sysctl: net.ipv4.conf.all.rp_filter=0
        - sysctl: net.ipv4.conf.lo.rp_filter=0
        - sysctl: net.ipv6.conf.all.disable_ipv6=0
        - sysctl: net.ipv6.conf.all.forwarding=1
        - sysctl: net.ipv6.conf.all.forwarding=1
        - sysctl: net.ipv6.conf.all.seg6_enabled=1
        - sysctl: net.ipv6.conf.default.seg6_enabled=1
  - name: S11
    image: akiranet24/frr:1.0
    interfaces:
        - inf: net0
          type: direct
          ipv4: 10.10.1.2/24
          peernode: R3
          peerinf: net1
    sysctls:
        - sysctl: net.ipv4.ip_forward=1
        - sysctl: net.ipv4.conf.all.rp_filter=0
        - sysctl: net.ipv4.conf.lo.rp_filter=0
        - sysctl: net.ipv6.conf.all.disable_ipv6=0
        - sysctl: net.ipv6.conf.all.forwarding=1
        - sysctl: net.ipv6.conf.all.forwarding=1
        - sysctl: net.ipv6.conf.all.seg6_enabled=1
        - sysctl: net.ipv6.conf.default.seg6_enabled=1
  - name: S12
    image: akiranet24/frr:1.0
    interfaces:
        - inf: net0
          type: direct
          ipv4: 10.10.2.2/24
          peernode: R4
          peerinf: net1
    sysctls:
        - sysctl: net.ipv4.ip_forward=1
        - sysctl: net.ipv4.conf.all.rp_filter=0
        - sysctl: net.ipv4.conf.lo.rp_filter=0
        - sysctl: net.ipv6.conf.all.disable_ipv6=0
        - sysctl: net.ipv6.conf.all.forwarding=1
        - sysctl: net.ipv6.conf.all.forwarding=1
        - sysctl: net.ipv6.conf.all.seg6_enabled=1
        - sysctl: net.ipv6.conf.default.seg6_enabled=1
  - name: S21
    image: akiranet24/frr:1.0
    interfaces:
        - inf: net0
          type: direct
          ipv4: 10.20.1.2/24
          peernode: R3
          peerinf: net2
    sysctls:
        - sysctl: net.ipv4.ip_forward=1
        - sysctl: net.ipv4.conf.all.rp_filter=0
        - sysctl: net.ipv4.conf.lo.rp_filter=0
        - sysctl: net.ipv6.conf.all.disable_ipv6=0
        - sysctl: net.ipv6.conf.all.forwarding=1
        - sysctl: net.ipv6.conf.all.forwarding=1
        - sysctl: net.ipv6.conf.all.seg6_enabled=1
        - sysctl: net.ipv6.conf.default.seg6_enabled=1
  - name: S22
    image: akiranet24/frr:1.0
    interfaces:
        - inf: net0
          type: direct
          ipv4: 10.20.2.2/24
          peernode: R4
          peerinf: net2
    sysctls:
        - sysctl: net.ipv4.ip_forward=1
        - sysctl: net.ipv4.conf.all.rp_filter=0
        - sysctl: net.ipv4.conf.lo.rp_filter=0
        - sysctl: net.ipv6.conf.all.disable_ipv6=0
        - sysctl: net.ipv6.conf.all.forwarding=1
        - sysctl: net.ipv6.conf.all.forwarding=1
        - sysctl: net.ipv6.conf.all.seg6_enabled=1
        - sysctl: net.ipv6.conf.default.seg6_enabled=1

node_config:
  - name: R1
    cmds:
      - cmd: ip addr add fc00:1::1/64 dev lo
      - cmd: ip -6 route add fc00:2::/64 via 2000::2
      - cmd: ip -6 route add fc00:3::/64 via 2001::2
      ##
      - cmd: ip sr tunsrc set fc00:1::1
      - cmd: ip -6 route add fc00:1::10 encap seg6local action End.B6.Encaps srh segs fc00:2::10 dev net0
      - cmd: ip -6 route add fc00:1::11 encap seg6local action End.DX6 nh6 2001::2 dev net0
  - name: R2
    cmds:
      - cmd: ip addr add fc00:2::1/64 dev lo
      - cmd: ip -6 route add fc00:1::/64 via 2000::1
      - cmd: ip -6 route add fc00:4::/64 via 2001::20
      ##
      - cmd: ip sr tunsrc set fc00:2::1
      - cmd: ip -6 route add fc00:2::10 encap seg6local action End.DX6 nh6 2001::20 dev net1
      - cmd: ip -6 route add fc00:2::11 encap seg6local action End.B6.Encaps srh segs fc00:1::11 dev net0
  - name: R3
    cmds:
      - cmd: ip addr add fc00:3::1/64 dev lo
      - cmd: ip -6 route add fc00:1::/64 via 2001::1
      ##
      - cmd: ip sr tunsrc set fc00:3::1
      - cmd: ip route add 10.10.2.0/24 encap seg6 mode encap segs fc00:1::10,fc00:4::10 dev net0
      - cmd: ip -6 route add fc00:3::11 encap seg6local action End.DX4 nh4 10.10.1.2 dev net0
  - name: R4
    cmds:
      - cmd: ip addr add fc00:4::1/64 dev lo
      - cmd: ip -6 route add fc00:2::/64 via 2001::10
      ##
      - cmd: ip sr tunsrc set fc00:4::1
      - cmd: ip -6 route add fc00:4::10 encap seg6local action End.DX4 nh4 10.10.2.2 dev net0
      - cmd: ip route add 10.10.1.0/24 encap seg6 mode encap segs fc00:2::11,fc00:3::11 dev net0

  - name: S11
    cmds:
      - cmd: ip route replace default via 10.10.1.1
  - name: S12
    cmds:
      - cmd: ip route replace default via 10.10.2.1
  - name: S21
    cmds:
      - cmd: ip route replace default via 10.20.1.1
  - name: S22
    cmds:
      - cmd: ip route replace default via 10.20.2.1

test:
  - name: p2p
    cmds:
      - cmd: docker exec S11 ping -c2 10.10.1.1
      - cmd: docker exec S11 ping -c2 10.10.1.2
      - cmd: docker exec S12 ping -c2 10.10.2.1
      - cmd: docker exec S12 ping -c2 10.10.2.2
      - cmd: docker exec S21 ping -c2 10.20.1.1
      - cmd: docker exec S21 ping -c2 10.20.1.2
      - cmd: docker exec S22 ping -c2 10.20.2.1
      - cmd: docker exec S22 ping -c2 10.20.2.2
      - cmd: docker exec R1 ping -c2 2000::1
      - cmd: docker exec R1 ping -c2 2000::2
      - cmd: docker exec R1 ping -c2 2001::1
      - cmd: docker exec R1 ping -c2 2001::2
      - cmd: docker exec R2 ping -c2 2000::1
      - cmd: docker exec R2 ping -c2 2000::2
      - cmd: docker exec R2 ping -c2 2001::10
      - cmd: docker exec R2 ping -c2 2001::20
      - cmd: docker exec R3 ping -c2 2001::1
      - cmd: docker exec R3 ping -c2 2001::2
      - cmd: docker exec R3 ping -c2 10.10.1.1
      - cmd: docker exec R3 ping -c2 10.10.1.2
      - cmd: docker exec R3 ping -c2 10.20.1.1
      - cmd: docker exec R3 ping -c2 10.20.1.2
      - cmd: docker exec R4 ping -c2 2001::10
      - cmd: docker exec R4 ping -c2 2001::20
      - cmd: docker exec R4 ping -c2 10.10.2.1
      - cmd: docker exec R4 ping -c2 10.10.2.2
      - cmd: docker exec R4 ping -c2 10.20.2.1
      - cmd: docker exec R4 ping -c2 10.20.2.2
  - name: bb
    cmds:
      - cmd: docker exec R1 ping -c2 fc00:1::1
      - cmd: docker exec R1 ping -c2 fc00:2::1
      - cmd: docker exec R1 ping -c2 fc00:3::1
      - cmd: docker exec R2 ping -c2 fc00:1::1
      - cmd: docker exec R2 ping -c2 fc00:2::1
      - cmd: docker exec R2 ping -c2 fc00:4::1
      - cmd: docker exec R3 ping -c2 fc00:1::1
      - cmd: docker exec R3 ping -c2 fc00:3::1
      - cmd: docker exec R4 ping -c2 fc00:2::1
      - cmd: docker exec R4 ping -c2 fc00:4::1
  - name: vpn
    cmds:
      - cmd: docker exec S11 ping -c2 10.10.2.2
      - cmd: docker exec S12 ping -c2 10.10.1.2
      # - cmd: docker exec S21 ping -c2 10.20.2.2
      # - cmd: docker exec S22 ping -c2 10.20.1.2
