nodes:
  - name: R0
    image: akiranet24/gobgp-frr:1.0
    interfaces:
        - name: net0
          type: direct
          ipv4: 192.168.100.10/24
          ipv6: fc00:a::10/64
          peer: R1
        - name: net1
          type: direct
          ipv4: 192.168.150.10/24
          ipv6: fc00:c::10/64
          peer: R2
    cmds:
        - cmd: /etc/init.d/frr start
        - cmd: >-
            vtysh -c "conf t"
            -c "router ospf"
            -c "network 192.168.100.0/24 area 0"
            -c "network 192.168.150.0/24 area 0"
    volumes:
        - volume: "test:/tmp/test"
    sysctls:
        - sysctl: net.ipv4.ip_forward=1
        - sysctl: net.ipv4.conf.all.rp_filter=0
        - sysctl: net.ipv4.conf.lo.rp_filter=0
        - sysctl: net.ipv6.conf.all.disable_ipv6=0
        - sysctl: net.ipv6.conf.all.forwarding=1
        - sysctl: net.ipv6.conf.all.seg6_enabled=1
        - sysctl: net.ipv6.conf.default.seg6_enabled=1
  - name: R1
    image: akiranet24/gobgp-frr:1.0
    interfaces:
        - name: net0
          type: direct
          ipv4: 192.168.100.11/24
          ipv6: fc00:a::11/64
          peer: R0
        - name: net1
          type: direct
          ipv4: 192.168.200.11/24
          ipv6: fc00:b::11/64
          peer: R2
    cmds:
        - cmd: /etc/init.d/frr start
        - cmd: >-
            vtysh -c "conf t"
            -c "router ospf"
            -c "network 192.168.100.0/24 area 0"
            -c "network 192.168.200.0/24 area 0"
    volumes:
        - volume: "test:/tmp/test"
    sysctls:
        - sysctl: net.ipv4.ip_forward=1
        - sysctl: net.ipv4.conf.all.rp_filter=0
        - sysctl: net.ipv4.conf.lo.rp_filter=0
        - sysctl: net.ipv6.conf.all.disable_ipv6=0
        - sysctl: net.ipv6.conf.all.forwarding=1
        - sysctl: net.ipv6.conf.all.forwarding=1
        - sysctl: net.ipv6.conf.all.seg6_enabled=1
        - sysctl: net.ipv6.conf.default.seg6_enabled=1
  - name: R2
    image: akiranet24/gobgp-frr:1.0
    interfaces:
        - name: net0
          type: direct
          ipv4: 192.168.200.12/24
          ipv6: fc00:b::12/64
          peer: R1
        - name: net1
          type: direct
          ipv4: 192.168.150.12/24
          ipv6: fc00:c::12/64
          peer: R0
    cmds:
        - cmd: /etc/init.d/frr start
        - cmd: >-
            vtysh -c "conf t"
            -c "router ospf"
            -c "network 192.168.200.0/24 area 0"
            -c "network 192.168.150.0/24 area 0"
    volumes:
        - volume: "test:/tmp/test"
    sysctls:
        - sysctl: net.ipv4.ip_forward=1
        - sysctl: net.ipv4.conf.all.rp_filter=0
        - sysctl: net.ipv4.conf.lo.rp_filter=0
        - sysctl: net.ipv6.conf.all.disable_ipv6=0
        - sysctl: net.ipv6.conf.all.forwarding=1
        - sysctl: net.ipv6.conf.all.forwarding=1
        - sysctl: net.ipv6.conf.all.seg6_enabled=1
        - sysctl: net.ipv6.conf.default.seg6_enabled=1
