nodes:
  - name: R1
    image: akiranet24/frr:1.0
    interfaces:
        - inf: net0
          type: direct
          ipv4: 10.0.0.1/30
          peernode: R2
          peerinf: net0
        - inf: net1
          type: direct
          ipv4: 10.0.0.9/30
          peernode: R3
          peerinf: net0
        - inf: net2
          type: direct
          ipv4: 10.0.0.17/30
          peernode: S1
          peerinf: net0
    cmds:
        - cmd: /etc/init.d/frr start
        - cmd: >-
            vtysh -c "conf t"
            -c "router ospf"
            -c " network 10.0.0.0/30 area 0"
            -c " network 10.0.0.8/30 area 0"
            -c " network 10.0.0.16/30 area 0"
    # volumes:
    #     - hostvolume: "test"
    #       containervolume: "/tmp/test"
    #     - hostvolume: "test"
    #       containervolume: "/tmp/test"
    sysctls:
        - sysctl: net.ipv4.ip_forward=1
        - sysctl: net.ipv4.conf.all.rp_filter=0
        - sysctl: net.ipv4.conf.lo.rp_filter=0
        - sysctl: net.ipv6.conf.all.disable_ipv6=0
        - sysctl: net.ipv6.conf.all.forwarding=1
        - sysctl: net.ipv6.conf.all.seg6_enabled=1
        - sysctl: net.ipv6.conf.default.seg6_enabled=1
  - name: R2
    image: akiranet24/frr:1.0
    interfaces:
        - inf: net0
          type: direct
          ipv4: 10.0.0.2/30
          peernode: R1
          peerinf: net0
        - inf: net1
          type: direct
          ipv4: 10.0.0.13/30
          peernode: R4
          peerinf: net0
    cmds:
        - cmd: /etc/init.d/frr start
        - cmd: >-
            vtysh -c "conf t"
            -c "router ospf"
            -c " network 10.0.0.0/30 area 0"
            -c " network 10.0.0.12/30 area 0"
    sysctls:
        - sysctl: net.ipv4.ip_forward=1
        - sysctl: net.ipv4.conf.all.rp_filter=0
        - sysctl: net.ipv4.conf.lo.rp_filter=0
        - sysctl: net.ipv6.conf.all.disable_ipv6=0
        - sysctl: net.ipv6.conf.all.forwarding=1
        - sysctl: net.ipv6.conf.all.forwarding=1
        - sysctl: net.ipv6.conf.all.seg6_enabled=1
        - sysctl: net.ipv6.conf.default.seg6_enabled=1
  - name: R3
    image: akiranet24/frr:1.0
    interfaces:
        - inf: net0
          type: direct
          ipv4: 10.0.0.10/30
          peernode: R1
          peerinf: net1
        - inf: net1
          type: direct
          ipv4: 10.0.0.5/30
          peernode: R4
          peerinf: net1
        - inf: net2
          type: direct
          ipv4: 10.0.0.21/30
          peernode: S3
          peerinf: net0
    cmds:
        - cmd: /etc/init.d/frr start
        - cmd: >-
            vtysh -c "conf t"
            -c "router ospf"
            -c " network 10.0.0.8/30 area 0"
            -c " network 10.0.0.4/30 area 0"
            -c " network 10.0.0.20/30 area 0"
    sysctls:
        - sysctl: net.ipv4.ip_forward=1
        - sysctl: net.ipv4.conf.all.rp_filter=0
        - sysctl: net.ipv4.conf.lo.rp_filter=0
        - sysctl: net.ipv6.conf.all.disable_ipv6=0
        - sysctl: net.ipv6.conf.all.forwarding=1
        - sysctl: net.ipv6.conf.all.forwarding=1
        - sysctl: net.ipv6.conf.all.seg6_enabled=1
        - sysctl: net.ipv6.conf.default.seg6_enabled=1
  - name: R4
    image: akiranet24/frr:1.0
    interfaces:
        - inf: net0
          type: direct
          ipv4: 10.0.0.14/30
          peernode: R2
          peerinf: net1
        - inf: net1
          type: direct
          ipv4: 10.0.0.6/30
          peernode: R3
          peerinf: net1
        - inf: net2
          type: direct
          ipv4: 10.0.0.25/30
          peernode: S4
          peerinf: net0
    cmds:
        - cmd: /etc/init.d/frr start
        - cmd: >-
            vtysh -c "conf t"
            -c "router ospf"
            -c " network 10.0.0.12/30 area 0"
            -c " network 10.0.0.4/30 area 0"
            -c " network 10.0.0.24/30 area 0"
    sysctls:
        - sysctl: net.ipv4.ip_forward=1
        - sysctl: net.ipv4.conf.all.rp_filter=0
        - sysctl: net.ipv4.conf.lo.rp_filter=0
        - sysctl: net.ipv6.conf.all.disable_ipv6=0
        - sysctl: net.ipv6.conf.all.forwarding=1
        - sysctl: net.ipv6.conf.all.forwarding=1
        - sysctl: net.ipv6.conf.all.seg6_enabled=1
        - sysctl: net.ipv6.conf.default.seg6_enabled=1
  - name: S1
    image: akiranet24/ubuntu:18.10
    interfaces:
        - inf: net0
          type: direct
          ipv4: 10.0.0.18/30
          peernode: R1
          peerinf: net2
    cmds:
        - cmd: ip route replace default via 10.0.0.17
    sysctls:
        - sysctl: net.ipv4.ip_forward=1
        - sysctl: net.ipv4.conf.all.rp_filter=0
        - sysctl: net.ipv4.conf.lo.rp_filter=0
        - sysctl: net.ipv6.conf.all.disable_ipv6=0
        - sysctl: net.ipv6.conf.all.forwarding=1
        - sysctl: net.ipv6.conf.all.forwarding=1
        - sysctl: net.ipv6.conf.all.seg6_enabled=1
        - sysctl: net.ipv6.conf.default.seg6_enabled=1
  - name: S3
    image: akiranet24/ubuntu:18.10
    interfaces:
        - inf: net0
          type: direct
          ipv4: 10.0.0.22/30
          peernode: R3
          peerinf: net2
    cmds:
        - cmd: ip route replace default via 10.0.0.21
    sysctls:
        - sysctl: net.ipv4.ip_forward=1
        - sysctl: net.ipv4.conf.all.rp_filter=0
        - sysctl: net.ipv4.conf.lo.rp_filter=0
        - sysctl: net.ipv6.conf.all.disable_ipv6=0
        - sysctl: net.ipv6.conf.all.forwarding=1
        - sysctl: net.ipv6.conf.all.forwarding=1
        - sysctl: net.ipv6.conf.all.seg6_enabled=1
        - sysctl: net.ipv6.conf.default.seg6_enabled=1
  - name: S4
    image: akiranet24/ubuntu:18.10
    interfaces:
        - inf: net0
          type: direct
          ipv4: 10.0.0.26/30
          peernode: R4
          peerinf: net2
    cmds:
        - cmd: ip route replace default via 10.0.0.25
    sysctls:
        - sysctl: net.ipv4.ip_forward=1
        - sysctl: net.ipv4.conf.all.rp_filter=0
        - sysctl: net.ipv4.conf.lo.rp_filter=0
        - sysctl: net.ipv6.conf.all.disable_ipv6=0
        - sysctl: net.ipv6.conf.all.forwarding=1
        - sysctl: net.ipv6.conf.all.forwarding=1
        - sysctl: net.ipv6.conf.all.seg6_enabled=1
        - sysctl: net.ipv6.conf.default.seg6_enabled=1
